import { useEffect, useRef } from 'react';

// We repeat the array 8 times (16 items total).
// This creates a massive track. We will animate it from 0% to -50% and snap back to loop perfectly.
const MARQUEE_ITEMS = Array(8).fill([
    'MUSIC COLLABORATION, REIMAGINED',
    'CONNECTING THE MISSING PIECES'
]).flat();

export default function ScrollMarquee() {
    const trackRef = useRef<HTMLDivElement>(null);
    const positionRef = useRef(0); // Current X translation percentage
    const velocityRef = useRef(0); // Extra speed generated by scrolling
    const lastScrollRef = useRef(typeof window !== 'undefined' ? window.scrollY : 0);

    useEffect(() => {
        let animId: number;

        // Track how fast the user is scrolling
        const onScroll = () => {
            const currentScroll = window.scrollY;
            const scrollDelta = currentScroll - lastScrollRef.current;

            // Add the scroll difference to our text velocity (tweak the 0.04 to make it more/less sensitive)
            velocityRef.current += scrollDelta * 0.01;
            lastScrollRef.current = currentScroll;
        };

        window.addEventListener('scroll', onScroll, { passive: true });

        const animate = () => {
            // 1. Base resting speed (constantly moving slowly to the left)
            let speed = -0.02;

            // 2. Add the temporary scroll velocity
            speed += velocityRef.current;

            // 3. Apply friction so the scroll speed smoothly decays back to 0
            velocityRef.current *= 0.88;

            // 4. Update the actual position
            positionRef.current += speed;

            // 5. Seamless Loop Logic (Snaps back to start seamlessly when it reaches exactly halfway)
            if (positionRef.current <= -50) {
                positionRef.current += 50;
            } else if (positionRef.current > 0) {
                // Prevents breaking if the user aggressively scrolls upwards
                positionRef.current -= 50;
            }

            // 6. Apply the physical transform to the DOM element
            if (trackRef.current) {
                trackRef.current.style.transform = `translateX(${positionRef.current}%)`;
            }

            animId = requestAnimationFrame(animate);
        };

        animId = requestAnimationFrame(animate);

        return () => {
            cancelAnimationFrame(animId);
            window.removeEventListener('scroll', onScroll);
        };
    }, []);

    return (
        <div className="marquee-section">
            <div className="marquee-track" ref={trackRef}>
                {MARQUEE_ITEMS.map((item, i) => (
                    <span className="marquee-item" key={i}>
            {item} <span className="marquee-star">✦</span>
          </span>
                ))}
            </div>
        </div>
    );
}